/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author JoTa
 */
public class rClientes extends javax.swing.JFrame {

        FondoPanel fondo = new FondoPanel ();
    /**
     * Creates new form rClientes
     */
    public rClientes() {
        this.setContentPane(fondo);
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(null);
        this.setTitle("Minimarket DuocUC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarCli = new javax.swing.JTextField();
        btnBuscarCl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnListarCl = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtBuscarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarCliActionPerformed(evt);
            }
        });

        btnBuscarCl.setText("Buscar");
        btnBuscarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClActionPerformed(evt);
            }
        });

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Run", "Nombre Completo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCliente);
        if (tblCliente.getColumnModel().getColumnCount() > 0) {
            tblCliente.getColumnModel().getColumn(0).setHeaderValue("Run");
            tblCliente.getColumnModel().getColumn(1).setHeaderValue("Nombre Completo");
            tblCliente.getColumnModel().getColumn(2).setHeaderValue("Telefono");
        }

        btnListarCl.setText("Listar Clientes");
        btnListarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese run Cliente a Bucar");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnListarCl)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCl)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCl)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1)
                    .addComponent(btnListarCl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarCliActionPerformed

    private void btnListarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClActionPerformed
        // TODO add your handling code here:
        String dvrun,nombre,appaterno,apmaterno;
        int idrun,telefono;

        Registro rg = new Registro();
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();

        modelo.setRowCount(0);

        List<Cliente> lista = rg.buscarTodosClientes();

        for (Cliente tmp : lista) {
            idrun = tmp.getIdrun();
            dvrun = tmp.getDvrun();
            nombre = tmp.getNombre();
            appaterno = tmp.getAppaterno();
            apmaterno = tmp.getApmaterno();
            telefono = tmp.getTelefono();

            modelo.addRow(new Object[]{idrun+"-"+dvrun, nombre+" "+appaterno+""+apmaterno , telefono});
            }
    }//GEN-LAST:event_btnListarClActionPerformed

    private void btnBuscarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClActionPerformed
        // TODO add your handling code here:
        
        String dvrun,nombre,appaterno,apmaterno;
        int idrun,telefono, id;

        Registro rg = new Registro();
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();

        try {
            id = Integer.parseInt(txtBuscarCli.getText());
        } catch (Exception e) {
            id = 0;
        }
        
        modelo.setRowCount(0);
           
        Cliente cli = rg.buscarPorIdCliente(id);
        idrun = cli.getIdrun();
        dvrun = cli.getDvrun();
        nombre = cli.getNombre();
        appaterno = cli.getAppaterno();
        apmaterno = cli.getApmaterno();
        telefono = cli.getTelefono();

        modelo.addRow(new Object[]{idrun+"-"+dvrun,nombre + " " + appaterno + " " + apmaterno,telefono});
            
    }//GEN-LAST:event_btnBuscarClActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tblCliente.getModel();
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCl;
    private javax.swing.JButton btnListarCl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBuscarCli;
    // End of variables declaration//GEN-END:variables
        class FondoPanel extends JPanel{
        private Image img;
        
        @Override
        public void paint (Graphics g){
        img = new ImageIcon(getClass().getResource("/imagenes/fondo.jpg")).getImage();
        
        g.drawImage(img, 0, 0, getWidth(),getHeight(), this);
        
        setOpaque(false);
        
        super.paint(g);
    }
        
    }

}
